### ISSUE TITLE
[Discussion] Functional patterns

### ISSUE THREAD

**Issue by SuperJMN** [zoran-horvat/easy-parse#1]
Hello, Zoran.

I've taken a look to the code and it's of wonderful quality, as I expected. 
However, I've observed that you don't make use of any of the functional patterns you told us about in some of your courses, like **Maybe** and **Either**.

Is it because they just don't fit in this domain? Is it because they would obscure the already complex logic? or just because they would be part of a future improvement?

Thanks!

PS: Congratulations for this project!!

**Comment by zoran-horvat** [comment]
The problem is that that approach is foreign to majority of programmers. I expected this project will be open-sourced at some point, and so I avoided elements that could cause confusion.

This decision shows up in compiler's return, for instance, which is System.Object - either a compiled object, or an error object. Caller is responsible to cast to compiled type before dereferencing the object.

On the other hand, I am using Option and Either in other projects, and they are serving me well.

Zoran
